eureka:
  instance:
    hostname: eclient-1
    serviceUrl:
      defaultZone: http://eureka-1:8761/eureka/,http://eureka-2:8761/eureka/
spring:
  datasource:
    url: jdbc:oracle:thin:@oracle12c:1521:xe
    username: workflow
    password: workflow
    driver-class-name: oracle.jdbc.OracleDriver
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
#=====================jpa config================================
  jpa:
      hibernate:
        ddl-auto: update
  #打印sql语句
      show-sql: true
#格式化输出的json字符串
  jackson:
      serialization:
        indent_output: true
